# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: src/proto/graph.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'src/proto/graph.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15src/proto/graph.proto\x12\x05graph\"\xa4\x01\n\x05Graph\x12\x1a\n\x05nodes\x18\x01 \x03(\x0b\x32\x0b.graph.Node\x12\x1a\n\x05\x65\x64ges\x18\x02 \x03(\x0b\x32\x0b.graph.Edge\x12\x30\n\nattributes\x18\x03 \x03(\x0b\x32\x1c.graph.Graph.AttributesEntry\x1a\x31\n\x0f\x41ttributesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x91\x01\n\x04Node\x12\n\n\x02id\x18\x01 \x01(\t\x12\x19\n\x04\x62\x61se\x18\x02 \x01(\x0e\x32\x0b.graph.Base\x12/\n\nattributes\x18\x03 \x03(\x0b\x32\x1b.graph.Node.AttributesEntry\x1a\x31\n\x0f\x41ttributesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xba\x01\n\x04\x45\x64ge\x12\x0e\n\x06source\x18\x01 \x01(\t\x12\x0e\n\x06target\x18\x02 \x01(\t\x12\x19\n\x11observation_count\x18\x03 \x01(\x05\x12\x13\n\x0bindividuals\x18\x04 \x03(\t\x12/\n\nattributes\x18\x05 \x03(\x0b\x32\x1b.graph.Edge.AttributesEntry\x1a\x31\n\x0f\x41ttributesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01*L\n\x04\x42\x61se\x12\x14\n\x10\x42\x41SE_UNSPECIFIED\x10\x00\x12\n\n\x06\x42\x41SE_A\x10\x01\x12\n\n\x06\x42\x41SE_C\x10\x02\x12\n\n\x06\x42\x41SE_G\x10\x03\x12\n\n\x06\x42\x41SE_T\x10\x04\x42\x03\xf8\x01\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.proto.graph_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\370\001\001'
  _globals['_GRAPH_ATTRIBUTESENTRY']._loaded_options = None
  _globals['_GRAPH_ATTRIBUTESENTRY']._serialized_options = b'8\001'
  _globals['_NODE_ATTRIBUTESENTRY']._loaded_options = None
  _globals['_NODE_ATTRIBUTESENTRY']._serialized_options = b'8\001'
  _globals['_EDGE_ATTRIBUTESENTRY']._loaded_options = None
  _globals['_EDGE_ATTRIBUTESENTRY']._serialized_options = b'8\001'
  _globals['_BASE']._serialized_start=536
  _globals['_BASE']._serialized_end=612
  _globals['_GRAPH']._serialized_start=33
  _globals['_GRAPH']._serialized_end=197
  _globals['_GRAPH_ATTRIBUTESENTRY']._serialized_start=148
  _globals['_GRAPH_ATTRIBUTESENTRY']._serialized_end=197
  _globals['_NODE']._serialized_start=200
  _globals['_NODE']._serialized_end=345
  _globals['_NODE_ATTRIBUTESENTRY']._serialized_start=148
  _globals['_NODE_ATTRIBUTESENTRY']._serialized_end=197
  _globals['_EDGE']._serialized_start=348
  _globals['_EDGE']._serialized_end=534
  _globals['_EDGE_ATTRIBUTESENTRY']._serialized_start=148
  _globals['_EDGE_ATTRIBUTESENTRY']._serialized_end=197
# @@protoc_insertion_point(module_scope)
